Add sitemap generator
starknet-io/starknet-website pull request #1835
Opened 2023-12-12 17:45 UTC by luisdralves

[Task](https://www.notion.so/untile/SEO-sitemap-ecae8ce23384465fa871218a498f669b?pvs=4)

This PR adds the ability to dynamically generate a sitemap based on the CMS content and the custom pages. It generates a single xml file because it is well under the size limits

2023-12-13 09:46 UTC, rafaelcruzazevedo requested changes

2023-12-13 09:46 UTC, rafaelcruzazevedo commented on workspaces/cms-scripts/src/sitemap.ts
> +const parsePageDirectory = async (dir: string, depth = 0) => {
why not a `Promise.all`

```js
const parsePageDirectory = async (dir, depth = 0) => {
  const files = await fs.readdir(dir);

  await Promise.all(files.map(async (filepath) => {
    ...
```

2023-12-13 09:46 UTC, rafaelcruzazevedo commented on workspaces/cms-scripts/src/sitemap.ts
> +const parseTutorials = async () => {
maybe we can simplify

```js
const parseTutorialFile = async (locale, filename) => {
  try {
    const file = await fs.readFile(`./public/data/tutorials/${locale}/${filename}`, 'utf8');
    const tutorial = JSON.parse(file);

    if (tutorial.type === 'youtube') {
      sitemapUrls.push({
        url: `/${locale}/tutorials/video/${tutorial.id}`,
        changefreq: 'monthly',
        priority: 0.6
      });
    }
  } catch {
    console.error(`Error parsing tutorial`, filename);
  }
};

const parseLocaleTutorials = async (locale) => {
  const files = await fs.readdir(`./public/data/tutorials/${locale}`);
  
  for (const filename of files) {
    await parseTutorialFile(locale, filename);
  }
};

const parseTutorials = async () => {
  for (const locale of locales) {
    await parseLocaleTutorials(locale);
  }
};
```

2023-12-14 16:05 UTC, nuno-aac approved these changes

2023-12-14 16:14 UTC, rafaelcruzazevedo approved these changes

2023-12-14 16:14 UTC, merged