Banner strip to the homepage
starknet-io/starknet-website pull request #2688
Opened 2024-03-18 10:30 UTC by TalBenAvi

2024-03-20 13:02 UTC, igalst requested changes

2024-03-20 13:02 UTC, igalst commented on workspaces/website/src/pages/(components)/NavbarStickyBanner/NavbarStickyBanner.tsx
> +          setIsOpen((prev) => !prev);
1. `setIsOpen(false);`
2. Move it to be part of `onClose`

2024-03-20 13:02 UTC, igalst commented on workspaces/website/src/pages/(components)/NavbarStickyBanner/NavbarStickyBanner.tsx
> +      top="78px"
Can we bring the header's height from a variable?

2024-03-20 13:02 UTC, igalst commented on workspaces/website/src/pages/(components)/NavbarStickyBanner/NavbarStickyBanner.tsx
> +      _dark={{ bgColor: "#A4A4EA" }}
use variable

2024-03-20 13:02 UTC, igalst commented on workspaces/website/src/pages/(components)/NavbarStickyBanner/NavbarStickyBanner.tsx
> +      bgColor={"snNavy"}
```suggestion
      bgColor="snNavy"
```

2024-03-20 13:02 UTC, igalst commented on workspaces/website/src/pages/(components)/NavbarStickyBanner/NavbarStickyBanner.tsx
> +      width="100%"
right=0 instead of width

2024-03-20 13:02 UTC, igalst commented on workspaces/website/src/pages/(components)/NavbarStickyBanner/NavbarStickyBanner.tsx
> +        <Button
remove border

2024-03-20 13:44 UTC, TalBenAvi commented on workspaces/website/src/pages/(components)/NavbarStickyBanner/NavbarStickyBanner.tsx
> +      top="78px"
the Header is determent by padding...don't think we can use it as requested.

![image](https://github.com/starknet-io/starknet-website/assets/91826661/dbad45dd-1ba1-4552-b119-bec7ad78c047)

2024-03-25 07:47 UTC, TalBenAvi commented on _data/pages/home.yml
>    - type: nav_sticky_banner
I don't think we really need this from my understanding this should be created from the cms I created it just for the developing stage.

2024-03-27 07:15 UTC, igalst approved these changes

2024-03-27 07:15 UTC, merged