Image icon link cards
starknet-io/starknet-website pull request #274
Opened 2023-04-14 13:34 UTC by milosyuki

This PR includes Image icon link card component with 3 variants: `image_icon_link_card`, `icon_link_card` and `dapp` and is being showcased in the storybook as well. This is the component made of different components displayed in the figma as "Home page cards". The only one's missing are Large card and Community card which will be covered in the next PR.

Also, home card icons are created and added to the storybook.

2023-04-18 09:59 UTC, robwalsh21 commented
> This PR includes Image icon link card component with 3 variants: `image_icon_link_card`, `icon_link_card` and `dapp` and is being showcased in the storybook as well. This is the component made of different components displayed in the figma as "Home page cards". The only one's missing are Large card and Community card which will be covered in the next PR.
> 
> Also, home card icons are created and added to the storybook.

hey @milosyuki   Noticing some issues on hover with cards on home and developers page 
<img width="1365" alt="CleanShot 2023-04-18 at 10 58 12@2x" src="https://user-images.githubusercontent.com/5764504/232742708-ffa87b12-e36f-4b65-82f2-81f293a0a33d.png">
<img width="1320" alt="CleanShot 2023-04-18 at 10 57 54@2x" src="https://user-images.githubusercontent.com/5764504/232742741-66af5c54-df51-4c7d-af10-478a150bfc61.png">

2023-04-19 10:40 UTC, robwalsh21 approved these changes

2023-04-19 10:40 UTC, robwalsh21 commented on _data/pages/en/developers.yml
@milosyuki I'm noticing some rendering issues with the  cards under courses in dark mode  
![CleanShot 2023-04-14 at 15 22 47](https://user-images.githubusercontent.com/5764504/232071498-85ddf156-4fdb-42db-92e7-da5c440c3745.png)

2023-04-19 10:40 UTC, robwalsh21 commented on _data/pages/en/home.yml
@milosyuki Another example of rendering issue with smaller card
![CleanShot 2023-04-14 at 15 26 30](https://user-images.githubusercontent.com/5764504/232072489-6280c350-a600-4ff9-869d-c48974dd81a9.png)

2023-04-19 12:35 UTC, thecotne requested changes
looks good overall just few comments

2023-04-19 12:35 UTC, thecotne commented on src/components/Icons/CardIcons/DappsIcon/DappsIcon.tsx
> +  const gradientIdPrefix = `gradient-${Math.random().toString(36).substr(2, 9)}`;
use this https://react.dev/reference/react/useId

2023-04-19 12:35 UTC, thecotne commented on src/app/[locale]/tutorials/(components)/TutorialsPage.tsx
> +console.log('hits ', hits)
this should be removed right?

2023-04-19 12:35 UTC, thecotne commented on src/blocks/cards/IconLinkCard.tsx
> +            {/* <Image src={icon} mb="20px" alt={title} /> */}
should this be removed instead of commenting it?

2023-04-19 12:35 UTC, thecotne commented on src/components/Card/style.css
> +/*! @algolia/autocomplete-theme-classic 1.7.4 | MIT License | © Algolia, Inc. and contributors | https://github.com/algolia/autocomplete */
this comment should be removed

2023-04-19 12:47 UTC, milosyuki commented on src/components/Icons/CardIcons/DappsIcon/DappsIcon.tsx
> +  const gradientIdPrefix = `gradient-${Math.random().toString(36).substr(2, 9)}`;
Thanks, fixed!

2023-04-19 12:48 UTC, milosyuki commented on src/app/[locale]/tutorials/(components)/TutorialsPage.tsx
> +console.log('hits ', hits)
Thanks, removed.

2023-04-19 12:48 UTC, milosyuki commented on src/blocks/cards/IconLinkCard.tsx
> +            {/* <Image src={icon} mb="20px" alt={title} /> */}
Thanks, removed.

2023-04-19 12:48 UTC, milosyuki commented on src/components/Card/style.css
> +/*! @algolia/autocomplete-theme-classic 1.7.4 | MIT License | © Algolia, Inc. and contributors | https://github.com/algolia/autocomplete */
Thanks, removed.

2023-04-19 13:18 UTC, thecotne approved these changes
👍

2023-04-19 14:10 UTC, milosyuki commented on _data/pages/en/developers.yml
Thanks, fixed.

2023-04-19 14:10 UTC, milosyuki commented on _data/pages/en/home.yml
Thanks, fixed.

2023-04-25 14:15 UTC, robwalsh21 commented
Did you get a chance to look at this @cxramina  ?

2023-04-25 14:17 UTC, cxramina commented
> Did you get a chance to look at this @cxramina ?

Yes, I send comments to Milos in Slack

2023-04-25 15:02 UTC, robwalsh21 commented
Great.  Thanks

2023-04-26 14:54 UTC, merged